function usStateData() {
    var selectInput;

    selectInput+='<option value="AL">Alabama</option>'
    selectInput+='<option value="AK">Alaska</option>'
    selectInput+='<option value="AZ">Arizona</option>'
    selectInput+='<option value="AR">Arkansas</option>'
    selectInput+='<option value="CA">California</option>'
    selectInput+='<option value="CO">Colorado</option>'
    selectInput+='<option value="CT">Connecticut</option>'
    selectInput+='<option value="DE">Delaware</option>'
    selectInput+='<option value="DC">District Of Columbia</option>'
    selectInput+='<option value="FL">Florida</option>'
    selectInput+='<option value="GA">Georgia</option>'
    selectInput+='<option value="HI">Hawaii</option>'
    selectInput+='<option value="ID">Idaho</option>'
    selectInput+='<option value="IL">Illinois</option>'
    selectInput+='<option value="IN">Indiana</option>'
    selectInput+='<option value="IA">Iowa</option>'
    selectInput+='<option value="KS">Kansas</option>'
    selectInput+='<option value="KY">Kentucky</option>'
    selectInput+='<option value="LA">Louisiana</option>'
    selectInput+='<option value="ME">Maine</option>'
    selectInput+='<option value="MD">Maryland</option>'
    selectInput+='<option value="MA">Massachusetts</option>'
    selectInput+='<option value="MI">Michigan</option>'
    selectInput+='<option value="MN">Minnesota</option>'
    selectInput+='<option value="MS">Mississippi</option>'
    selectInput+='<option value="MO">Missouri</option>'
    selectInput+='<option value="MT">Montana</option>'
    selectInput+='<option value="NE">Nebraska</option>'
    selectInput+='<option value="NV">Nevada</option>'
    selectInput+='<option value="NH">New Hampshire</option>'
    selectInput+='<option value="NJ">New Jersey</option>'
    selectInput+='<option value="NM">New Mexico</option>'
    selectInput+='<option value="NY">New York</option>'
    selectInput+='<option value="NC">North Carolina</option>'
    selectInput+='<option value="ND">North Dakota</option>'
    selectInput+='<option value="OH">Ohio</option>'
    selectInput+='<option value="OK">Oklahoma</option>'
    selectInput+='<option value="OR">Oregon</option>'
    selectInput+='<option value="PA">Pennsylvania</option>'
    selectInput+='<option value="RI">Rhode Island</option>'
    selectInput+='<option value="SC">South Carolina</option>'
    selectInput+='<option value="SD">South Dakota</option>'
    selectInput+='<option value="TN">Tennessee</option>'
    selectInput+='<option value="TX">Texas</option>'
    selectInput+='<option value="UT">Utah</option>'
    selectInput+='<option value="VT">Vermont</option>'
    selectInput+='<option value="VA">Virginia</option>'
    selectInput+='<option value="WA">Washington</option>'
    selectInput+='<option value="WV">West Virginia</option>'
    selectInput+='<option value="WI">Wisconsin</option>'
    selectInput+='<option value="WY">Wyoming</option>'

    return selectInput;
}